### ISSUE TITLE
graph_replace Key Error

### ISSUE THREAD

**Issue by gtshs2** [poolio/unrolled_gan#3]
When I run the code,
Key error occurs on 'cur_update_dict = graph_replace(update_dict, cur_update_dict)' line in the for-loop.
How can I fix it ?!
I use python3.5, tensorflow 1.0.

**Comment by poolio** [comment]
Thanks for spotting this! There's a bug in `graph_replace` in TF 1.0: https://github.com/tensorflow/tensorflow/issues/9125

I've put together a small PR that fixes the problem here: https://github.com/poolio/tensorflow/pull/1/files

For now I'm going to leave the notebook as is (which works on TF < 1.0), and will update it to TF 1.0 once the bug is fixed.

**Comment by royaurko** [comment]
Hi Ben,

I also ran into the same problem. Is there any other way to do the unrolling without having to recompile or rollback tensorflow?

**Comment by poolio** [comment]
@royaurko I added this hack to get `graph_replace` working in TF 1.0:
```
_graph_replace = tf.contrib.graph_editor.graph_replace

def remove_original_op_attributes(graph):
    """Remove _original_op attribute from all operations in a graph."""
    for op in graph.get_operations():
        op._original_op = None
        
def graph_replace(*args, **kwargs):
    """Monkey patch graph_replace so that it works with TF 1.0"""
    remove_original_op_attributes(tf.get_default_graph())
    return _graph_replace(*args, **kwargs)
```

The current notebook in the repo should work again!
